kind: Pod
apiVersion: v1
metadata:
  name: k8s-pod
spec:
  volumes:
    - name: pvc
      persistentVolumeClaim:
       claimName: pvc
  containers:
    - name: pvc-pod
      image: eu.gcr.io/container:latest
      volumeMounts:
        - mountPath: "/tmp"
          name: pvc
